# Generated by Django 4.0.3 on 2022-04-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstame', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=200)),
            ],
        ),
    ]
