# Generated by Django 4.0.3 on 2022-04-13 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='firstame',
            new_name='firstname',
        ),
    ]
